name: Build Docker Image & Deploy to EC2 (No Registry)

on:
  push:
    branches: [ master ]

concurrency:
  group: deploy-ec2
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.APP_NAME }}     # spring-app
      APP_PORT: ${{ secrets.APP_PORT }}       # 8080
      TAR_DIR: ./artifacts
      OUT_DIR_EC2: /home/ec2-user/spring2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- JDK & Maven 캐시 ----
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # ---- Maven 빌드 ----
      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      # ---- Docker 이미지 빌드 ----
      - name: Build Docker image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG="sha-${SHORT_SHA}"
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -t ${IMAGE_NAME}:latest .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Save image as tar.gz
        run: |
          mkdir -p "${TAR_DIR}"
          TAR_FILE="${TAR_DIR}/${IMAGE_NAME}-${IMAGE_TAG}.tar"
          docker save -o "${TAR_FILE}" "${IMAGE_NAME}:${IMAGE_TAG}"
          gzip -f "${TAR_FILE}"
          ls -lh "${TAR_FILE}.gz"

      - name: Make tar readable for scp
        run: |
          chmod 755 artifacts
          chmod 644 artifacts/*.tar.gz
          ls -l artifacts

      # ---- EC2로 이미지 복사 ----
      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7    # ← v0.1.7로
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "artifacts/*.tar.gz"
          target: "${{ env.OUT_DIR_EC2 }}"
          overwrite: true
          strip_components: 1 

      # ---- EC2에서 컨테이너 재기동 ----
      - name: Deploy container on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd "${{ env.OUT_DIR_EC2 }}"
            LATEST_GZ=$(ls -t "${{ env.IMAGE_NAME }}"-sha-*.tar.gz | head -n1)
            TAR_FILE="${LATEST_GZ%.gz}"

            echo "[1/4] Load new image"
            docker rmi "${{ env.IMAGE_NAME }}":latest 2>/dev/null || true
            gunzip -f "${LATEST_GZ}"
            docker load -i "${TAR_FILE}"

            NEW_TAG=$(basename "${TAR_FILE}" | sed -E 's/^'"${{ env.IMAGE_NAME }}"'-([^.]*)\.tar$/\1/')
            docker tag "${{ env.IMAGE_NAME }}:${NEW_TAG}" "${{ env.IMAGE_NAME }}:latest" || true

            echo "[2/4] Stop & remove old container"
            docker stop "${{ env.IMAGE_NAME }}" 2>/dev/null || true
            docker rm   "${{ env.IMAGE_NAME }}" 2>/dev/null || true

            echo "[3/4] Run new container"
            docker run -d --name "${{ env.IMAGE_NAME }}" \
              --network my-net \
              -p "${{ env.APP_PORT }}:${{ env.APP_PORT }}" \
              -e "SPRING_PROFILES_ACTIVE=prod" \
              -e ORACLE_URL=jdbc:oracle:thin:@oracle-container:1521:xe \
              --restart=always \
              "${{ env.IMAGE_NAME }}:${NEW_TAG}"

            echo "[4/4] Clean up old images/tar files"
            ls -t "${{ env.IMAGE_NAME }}"-sha-*.tar | awk 'NR>3 {print $1}' | xargs -r rm -f || true
            docker image prune -f || true

            echo "Deployed! ${{ env.IMAGE_NAME }}:${NEW_TAG}"